source "https://rubygems.org"
gem "turbot", github: "OpenAddressesUK/turbot-client"
gem "turbot-runner", github: "OpenAddressesUK/turbot-runner"
gem "openc-schema", github: "OpenAddressesUK/openc-schema"
gem "turbot-api", github: "OpenAddressesUK/turbot-api"
